security:
  encoders:
    App\Entity\User:
      algorithm: auto
    Symfony\Component\Security\Core\User\User: plaintext
  providers:
    in_memory:
      memory:
        users:
          MyAdmin:
            password: ezcheckincontrase;a
            roles: "ROLE_SUPER_ADMIN"
    app_user_provider:
      entity:
        class: App\Entity\User
        property: email
    chain_provider:
      chain:
        providers: [in_memory, app_user_provider]
  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      anonymous: true
      provider: chain_provider
      guard:
        authenticators:
          - App\Security\LoginFormAuthenticator
      logout:
        path: app_logout
        target: app_home
  # Easy way to control access for large sections of your site
  # Note: Only the *first* access control that matches will be used
  access_control:
    - { path: ^/admin, roles: [ROLE_SUPER_ADMIN, ROLE_ADMIN] }
    - { path: ^/profesor, roles: ROLE_PROFESSOR }
    - { path: ^/tutor, roles: [ROLE_TUTOR] }
  role_hierarchy:
    ROLE_SUPER_ADMIN:
      - ROLE_ADMIN
      - ROLE_ALLOWED_TO_SWITCH
    ROLE_ADMIN:
      - ROLE_PROFESSOR
      - ROLE_SONATA_ADMIN
    ROLE_PROFESSOR:
      - ROLE_USER
    ROLE_TUTOR:
      - ROLE_USER
